-- ════════════════════════════════════════════════════════════════════════
-- XUẤT TOÀN BỘ DỮ LIỆU MỘT DỰ ÁN — bản dùng với psql
-- DỰ ÁN: 26-VPI-I-113
--
-- CHỈ ĐỌC: toàn bộ file là câu SELECT, không ghi/sửa/xoá gì trên prod.
--
-- KIỂM TRA TRƯỚC (mã dự án phải khớp chính xác, sai một ký tự là ra file rỗng):
--   SELECT id, project_code, project_name FROM projects WHERE project_code = '26-VPI-I-113';
-- ════════════════════════════════════════════════════════════════════════

-- CÁCH CHẠY:
--   psql "<PROD_URL>" -v ON_ERROR_STOP=1 -A -t -q -f export-26-VPI-I-113.sql > 26-VPI-I-113_dump.sql
--
-- Kết quả 26-VPI-I-113_dump.sql là các câu INSERT (đã xếp cha trước con), gửi lại cho bên lab.
-- ON CONFLICT DO NOTHING → nạp lại nhiều lần không nhân bản.

SELECT '-- users';
SELECT format('INSERT INTO "users" ("id", "username", "email", "password_hash", "full_name", "role_code", "user_level", "department_id", "is_active", "created_at", "updated_at", "telegram_chat_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."username", t."email", t."password_hash", t."full_name", t."role_code", t."user_level", t."department_id", t."is_active", t."created_at", t."updated_at", t."telegram_chat_id") FROM "users" t WHERE (id in (select assigned_to from workflow_tasks where project_id = (select id from projects where project_code = '26-VPI-I-113') and assigned_to is not null) OR id in (select welder_id from weld_joints where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and welder_id is not null) OR id in (select author_id from tech_comments where pr_item_id in (select id from purchase_request_items where pr_id in (select id from purchase_requests where project_id = (select id from projects where project_code = '26-VPI-I-113'))) and author_id is not null));

SELECT '-- materials';
SELECT format('INSERT INTO "materials" ("id", "material_code", "name", "unit", "category", "min_stock", "current_stock", "unit_price", "currency", "created_at", "updated_at", "grade", "name_en", "reserved_stock", "specification", "status", "is_provisional", "created_by_unit", "group_code", "promoted_to_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."material_code", t."name", t."unit", t."category", t."min_stock", t."current_stock", t."unit_price", t."currency", t."created_at", t."updated_at", t."grade", t."name_en", t."reserved_stock", t."specification", t."status", t."is_provisional", t."created_by_unit", t."group_code", t."promoted_to_id") FROM "materials" t WHERE (id in (select material_id from stock_movements where project_id = (select id from projects where project_code = '26-VPI-I-113') and material_id is not null) OR id in (select material_id from purchase_request_items where pr_id in (select id from purchase_requests where project_id = (select id from projects where project_code = '26-VPI-I-113')) and material_id is not null) OR id in (select material_id from purchase_order_items where po_id in (select id from purchase_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and material_id is not null) OR id in (select material_id from material_issues where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and material_id is not null) OR id in (select material_id from bom_items where bom_id in (select id from bill_of_materials where project_id = (select id from projects where project_code = '26-VPI-I-113')) and material_id is not null) OR id in (select material_id from work_order_material_requests where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and material_id is not null) OR id in (select material_id from hard_peggings where project_id = (select id from projects where project_code = '26-VPI-I-113') and material_id is not null) OR id in (select material_id from work_order_material_requests where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and material_id is not null));

SELECT '-- vendors';
SELECT format('INSERT INTO "vendors" ("id", "vendor_code", "name", "contact_name", "email", "phone", "address", "country", "category", "rating", "is_active", "notes", "created_at", "updated_at", "short_name", "tax_code", "city", "website", "contact_title", "contact_phone", "contact_email", "vendor_type", "bank", "account_no", "blacklisted") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."vendor_code", t."name", t."contact_name", t."email", t."phone", t."address", t."country", t."category", t."rating", t."is_active", t."notes", t."created_at", t."updated_at", t."short_name", t."tax_code", t."city", t."website", t."contact_title", t."contact_phone", t."contact_email", t."vendor_type", t."bank", t."account_no", t."blacklisted") FROM "vendors" t WHERE (id in (select vendor_id from subcontractor_contracts where project_id = (select id from projects where project_code = '26-VPI-I-113') and vendor_id is not null) OR id in (select vendor_id from purchase_orders where project_id = (select id from projects where project_code = '26-VPI-I-113') and vendor_id is not null) OR id in (select vendor_id from invoices where project_id = (select id from projects where project_code = '26-VPI-I-113') and vendor_id is not null) OR id in (select vendor_id from drawdown_beneficiary_lines where invoice_id in (select id from invoices where project_id = (select id from projects where project_code = '26-VPI-I-113')) and vendor_id is not null) OR id in (select vendor_id from purchase_contracts where project_id = (select id from projects where project_code = '26-VPI-I-113') and vendor_id is not null) OR id in (select vendor_id from bid_quote_vendors where bid_id in (select id from bid_analyses where project_id = (select id from projects where project_code = '26-VPI-I-113')) and vendor_id is not null));

SELECT '-- workshops';
SELECT format('INSERT INTO "workshops" ("id", "code", "name", "name_en", "capacity") VALUES (%L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."code", t."name", t."name_en", t."capacity") FROM "workshops" t WHERE (id in (select workshop_id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113') and workshop_id is not null));

SELECT '-- employees';
SELECT format('INSERT INTO "employees" ("id", "employee_code", "user_id", "full_name", "date_of_birth", "gender", "phone", "email", "address", "id_number", "tax_code", "social_ins_no", "bank_account", "bank_name", "department_id", "position", "employment_type", "join_date", "leave_date", "status", "dependents", "distance_km", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."employee_code", t."user_id", t."full_name", t."date_of_birth", t."gender", t."phone", t."email", t."address", t."id_number", t."tax_code", t."social_ins_no", t."bank_account", t."bank_name", t."department_id", t."position", t."employment_type", t."join_date", t."leave_date", t."status", t."dependents", t."distance_km", t."created_at", t."updated_at") FROM "employees" t WHERE (id in (select employee_id from timesheets where project_id = (select id from projects where project_code = '26-VPI-I-113') and employee_id is not null));

SELECT '-- loan_drawdowns';
SELECT format('INSERT INTO "loan_drawdowns" ("id", "drawdown_no", "contract_id", "amount_funded_vnd", "request_date", "execution_date", "due_date", "status", "created_by", "approved_by", "executed_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."drawdown_no", t."contract_id", t."amount_funded_vnd", t."request_date", t."execution_date", t."due_date", t."status", t."created_by", t."approved_by", t."executed_by", t."created_at", t."updated_at") FROM "loan_drawdowns" t WHERE (id in (select drawdown_id from drawdown_beneficiary_lines where invoice_id in (select id from invoices where project_id = (select id from projects where project_code = '26-VPI-I-113')) and drawdown_id is not null));

SELECT '-- departments';
SELECT format('INSERT INTO "departments" ("id", "code", "name", "name_en", "parent_id") VALUES (%L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."code", t."name", t."name_en", t."parent_id") FROM "departments" t WHERE (id in (select department_id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113') and department_id is not null) OR id in (select department_id from equipment_assignments where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and department_id is not null) OR id in (select department_id from material_request_orders where project_id = (select id from projects where project_code = '26-VPI-I-113') and department_id is not null));

SELECT '-- equipment';
SELECT format('INSERT INTO "equipment" ("id", "equipment_code", "name", "category", "model", "serial_no", "manufacturer", "location", "department_id", "status", "condition", "purchase_date", "inspection_due", "last_inspection", "notes", "created_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."equipment_code", t."name", t."category", t."model", t."serial_no", t."manufacturer", t."location", t."department_id", t."status", t."condition", t."purchase_date", t."inspection_due", t."last_inspection", t."notes", t."created_by", t."created_at", t."updated_at") FROM "equipment" t WHERE (id in (select equipment_id from equipment_assignments where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and equipment_id is not null));

SELECT '-- warehouses';
SELECT format('INSERT INTO "warehouses" ("id", "code", "name", "project_code", "kind", "is_active", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."code", t."name", t."project_code", t."kind", t."is_active", t."created_at") FROM "warehouses" t WHERE (id in (select warehouse_id from stock_movements where project_id = (select id from projects where project_code = '26-VPI-I-113') and warehouse_id is not null));

SELECT '-- certificate_registry';
SELECT format('INSERT INTO "certificate_registry" ("id", "cert_type", "cert_number", "holder_name", "holder_id", "issued_by", "issue_date", "expiry_date", "standard", "scope", "file_url", "is_active", "created_at", "renewed_from_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."cert_type", t."cert_number", t."holder_name", t."holder_id", t."issued_by", t."issue_date", t."expiry_date", t."standard", t."scope", t."file_url", t."is_active", t."created_at", t."renewed_from_id") FROM "certificate_registry" t WHERE (id in (select welder_cert_id from weld_joints where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and welder_cert_id is not null) OR id in (select wps_cert_id from weld_joints where work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113')) and wps_cert_id is not null));

SELECT '-- mill_certificates';
SELECT format('INSERT INTO "mill_certificates" ("id", "cert_number", "material_id", "vendor_id", "heat_number", "grade", "thickness", "chem_composition", "mech_properties", "file_url", "is_verified", "verified_by", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."cert_number", t."material_id", t."vendor_id", t."heat_number", t."grade", t."thickness", t."chem_composition", t."mech_properties", t."file_url", t."is_verified", t."verified_by", t."created_at") FROM "mill_certificates" t WHERE (id in (select mill_certificate_id from stock_movements where project_id = (select id from projects where project_code = '26-VPI-I-113') and mill_certificate_id is not null));

SELECT '-- ledger_import_batches';
SELECT format('INSERT INTO "ledger_import_batches" ("id", "file_name", "note", "row_count", "matched_rows", "total_debit", "total_credit", "imported_by", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."file_name", t."note", t."row_count", t."matched_rows", t."total_debit", t."total_credit", t."imported_by", t."created_at") FROM "ledger_import_batches" t WHERE (id in (select batch_id from ledger_entries where project_id = (select id from projects where project_code = '26-VPI-I-113') and batch_id is not null));

SELECT '-- projects';
SELECT format('INSERT INTO "projects" ("id", "project_code", "project_name", "client_name", "product_type", "contract_value", "currency", "status", "start_date", "end_date", "pm_user_id", "description", "created_at", "updated_at", "project_type", "sale_customer_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_code", t."project_name", t."client_name", t."product_type", t."contract_value", t."currency", t."status", t."start_date", t."end_date", t."pm_user_id", t."description", t."created_at", t."updated_at", t."project_type", t."sale_customer_id") FROM "projects" t WHERE project_code = '26-VPI-I-113';

SELECT '-- workflow_tasks';
SELECT format('INSERT INTO "workflow_tasks" ("id", "project_id", "step_code", "step_name", "step_name_en", "description", "assigned_role", "assigned_to", "status", "priority", "deadline", "started_at", "completed_at", "completed_by", "result_data", "notes", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."step_code", t."step_name", t."step_name_en", t."description", t."assigned_role", t."assigned_to", t."status", t."priority", t."deadline", t."started_at", t."completed_at", t."completed_by", t."result_data", t."notes", t."created_at", t."updated_at") FROM "workflow_tasks" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- daily_production_logs';
SELECT format('INSERT INTO "daily_production_logs" ("id", "project_id", "lsx_code", "wbs_stage", "report_date", "reported_volume", "team_user_id", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."lsx_code", t."wbs_stage", t."report_date", t."reported_volume", t."team_user_id", t."created_at") FROM "daily_production_logs" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- project_finance_plans';
SELECT format('INSERT INTO "project_finance_plans" ("id", "project_id", "customer_id", "scope_description", "contract_value", "status", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."customer_id", t."scope_description", t."contract_value", t."status", t."created_at", t."updated_at") FROM "project_finance_plans" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- weekly_acceptance_logs';
SELECT format('INSERT INTO "weekly_acceptance_logs" ("id", "project_id", "lsx_code", "week_number", "role", "accepted_volume", "inspector_id", "notes", "created_at", "reported_total", "task_id", "week_end_date", "week_start_date", "year") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."lsx_code", t."week_number", t."role", t."accepted_volume", t."inspector_id", t."notes", t."created_at", t."reported_total", t."task_id", t."week_end_date", t."week_start_date", t."year") FROM "weekly_acceptance_logs" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- stock_movements';
SELECT format('INSERT INTO "stock_movements" ("id", "material_id", "project_id", "type", "quantity", "reason", "reference_no", "performed_by", "notes", "created_at", "heat_number", "lot_number", "po_item_id", "warehouse_id", "mill_certificate_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."material_id", t."project_id", t."type", t."quantity", t."reason", t."reference_no", t."performed_by", t."notes", t."created_at", t."heat_number", t."lot_number", t."po_item_id", t."warehouse_id", t."mill_certificate_id") FROM "stock_movements" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- hse_man_hours';
SELECT format('INSERT INTO "hse_man_hours" ("id", "period_year", "period_month", "project_id", "man_hours", "source", "note", "created_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."period_year", t."period_month", t."project_id", t."man_hours", t."source", t."note", t."created_by", t."created_at", t."updated_at") FROM "hse_man_hours" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- tasks';
SELECT format('INSERT INTO "tasks" ("id", "project_id", "parent_id", "level", "task_type", "title", "description", "status", "priority", "deadline", "created_by", "assigned_at", "started_at", "completed_at", "completed_by", "result_data", "checklist_template_key", "checklist_state", "return_count", "created_at", "updated_at", "hook_keys", "template_step_id", "forwarded_from_id", "blocked", "escalated", "escalated_at", "escalated_by", "external_ref", "external_source", "submitted_at", "bom_version_id", "revision_round", "revision_id", "origin_step_code", "skip_reason") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."parent_id", t."level", t."task_type", t."title", t."description", t."status", t."priority", t."deadline", t."created_by", t."assigned_at", t."started_at", t."completed_at", t."completed_by", t."result_data", t."checklist_template_key", t."checklist_state", t."return_count", t."created_at", t."updated_at", t."hook_keys", t."template_step_id", t."forwarded_from_id", t."blocked", t."escalated", t."escalated_at", t."escalated_by", t."external_ref", t."external_source", t."submitted_at", t."bom_version_id", t."revision_round", t."revision_id", t."origin_step_code", t."skip_reason") FROM "tasks" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- meetings';
SELECT format('INSERT INTO "meetings" ("id", "project_id", "title", "agenda", "location", "starts_at", "ends_at", "mom_number", "status", "minutes_note", "created_by", "created_at", "updated_at", "minutes_data", "task_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."title", t."agenda", t."location", t."starts_at", t."ends_at", t."mom_number", t."status", t."minutes_note", t."created_by", t."created_at", t."updated_at", t."minutes_data", t."task_id") FROM "meetings" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- budgets';
SELECT format('INSERT INTO "budgets" ("id", "project_id", "category", "planned", "actual", "committed", "forecast", "month", "year", "notes", "created_at", "updated_at", "bom_version_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."category", t."planned", t."actual", t."committed", t."forecast", t."month", t."year", t."notes", t."created_at", t."updated_at", t."bom_version_id") FROM "budgets" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- project_baselines';
SELECT format('INSERT INTO "project_baselines" ("id", "project_id", "version", "label", "frozen_at", "frozen_by", "snapshot", "is_active", "notes", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."version", t."label", t."frozen_at", t."frozen_by", t."snapshot", t."is_active", t."notes", t."created_at", t."updated_at") FROM "project_baselines" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- project_submissions';
SELECT format('INSERT INTO "project_submissions" ("id", "external_ref", "status", "payload", "sale_customer_id", "project_id", "project_code", "reason", "reviewed_by", "reviewed_at", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."external_ref", t."status", t."payload", t."sale_customer_id", t."project_id", t."project_code", t."reason", t."reviewed_by", t."reviewed_at", t."created_at", t."updated_at") FROM "project_submissions" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- piece_rate_contracts';
SELECT format('INSERT INTO "piece_rate_contracts" ("id", "contract_code", "project_id", "team_code", "work_type", "unit_price", "unit", "contract_value", "start_date", "end_date", "status", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."contract_code", t."project_id", t."team_code", t."work_type", t."unit_price", t."unit", t."contract_value", t."start_date", t."end_date", t."status", t."created_at", t."updated_at") FROM "piece_rate_contracts" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- norms';
SELECT format('INSERT INTO "norms" ("id", "project_id", "category", "code", "name", "unit", "rate", "basis_unit", "material_id", "notes", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."category", t."code", t."name", t."unit", t."rate", t."basis_unit", t."material_id", t."notes", t."created_at", t."updated_at") FROM "norms" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- labor_rates';
SELECT format('INSERT INTO "labor_rates" ("id", "stage", "stage_name", "sub_item", "unit_price", "unit", "revision", "effective_date", "project_id", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."stage", t."stage_name", t."sub_item", t."unit_price", t."unit", t."revision", t."effective_date", t."project_id", t."created_at", t."updated_at") FROM "labor_rates" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- mrb_releases';
SELECT format('INSERT INTO "mrb_releases" ("id", "project_id", "revision", "status", "snapshot", "released_by_id", "released_at", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."revision", t."status", t."snapshot", t."released_by_id", t."released_at", t."created_at") FROM "mrb_releases" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- project_settlements';
SELECT format('INSERT INTO "project_settlements" ("id", "project_id", "revenue_contract", "revenue_invoiced", "revenue_collected", "cost_material", "cost_labor", "cost_service", "cost_other", "total_cost", "profit", "margin_pct", "status", "snapshot", "notes", "created_by", "submitted_at", "approved_by", "approved_at", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."revenue_contract", t."revenue_invoiced", t."revenue_collected", t."cost_material", t."cost_labor", t."cost_service", t."cost_other", t."total_cost", t."profit", t."margin_pct", t."status", t."snapshot", t."notes", t."created_by", t."submitted_at", t."approved_by", t."approved_at", t."created_at", t."updated_at") FROM "project_settlements" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- packing_lists';
SELECT format('INSERT INTO "packing_lists" ("id", "pl_code", "project_id", "status", "total_weight", "total_pieces", "dimensions", "notes", "created_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."pl_code", t."project_id", t."status", t."total_weight", t."total_pieces", t."dimensions", t."notes", t."created_by", t."created_at", t."updated_at") FROM "packing_lists" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- shipments';
SELECT format('INSERT INTO "shipments" ("id", "shipment_code", "project_id", "status", "vehicle_no", "driver_name", "driver_phone", "destination", "shipped_at", "arrived_at", "received_by", "received_at", "total_weight", "total_pieces", "notes", "created_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."shipment_code", t."project_id", t."status", t."vehicle_no", t."driver_name", t."driver_phone", t."destination", t."shipped_at", t."arrived_at", t."received_by", t."received_at", t."total_weight", t."total_pieces", t."notes", t."created_by", t."created_at", t."updated_at") FROM "shipments" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- timesheets';
SELECT format('INSERT INTO "timesheets" ("id", "employee_id", "project_id", "work_date", "hours_regular", "hours_ot", "task_description", "status", "approved_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."employee_id", t."project_id", t."work_date", t."hours_regular", t."hours_ot", t."task_description", t."status", t."approved_by", t."created_at", t."updated_at") FROM "timesheets" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- cashflow_entries';
SELECT format('INSERT INTO "cashflow_entries" ("id", "entry_code", "project_id", "type", "category", "amount", "description", "entry_date", "reference", "status", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."entry_code", t."project_id", t."type", t."category", t."amount", t."description", t."entry_date", t."reference", t."status", t."created_at", t."updated_at") FROM "cashflow_entries" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- change_events';
SELECT format('INSERT INTO "change_events" ("id", "project_id", "source_step", "source_model", "source_id", "event_type", "target_model", "target_id", "data_before", "data_after", "reason", "triggered_by", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."source_step", t."source_model", t."source_id", t."event_type", t."target_model", t."target_id", t."data_before", t."data_after", t."reason", t."triggered_by", t."created_at") FROM "change_events" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- lesson_learned';
SELECT format('INSERT INTO "lesson_learned" ("id", "project_id", "category", "description", "root_cause", "action_taken", "recommendation", "submitted_by", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."category", t."description", t."root_cause", t."action_taken", t."recommendation", t."submitted_by", t."created_at") FROM "lesson_learned" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- inspection_test_plans';
SELECT format('INSERT INTO "inspection_test_plans" ("id", "itp_code", "project_id", "name", "revision", "status", "approved_by", "approved_at", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."itp_code", t."project_id", t."name", t."revision", t."status", t."approved_by", t."approved_at", t."created_at", t."updated_at") FROM "inspection_test_plans" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- safety_incidents';
SELECT format('INSERT INTO "safety_incidents" ("id", "incident_code", "project_id", "incident_date", "severity", "category", "location", "description", "root_cause", "corrective_action", "reported_by", "status", "resolved_at", "created_at", "updated_at", "investigated_by", "investigation_date", "closed_by", "closed_at", "lost_time_days", "task_id", "recordable") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."incident_code", t."project_id", t."incident_date", t."severity", t."category", t."location", t."description", t."root_cause", t."corrective_action", t."reported_by", t."status", t."resolved_at", t."created_at", t."updated_at", t."investigated_by", t."investigation_date", t."closed_by", t."closed_at", t."lost_time_days", t."task_id", t."recordable") FROM "safety_incidents" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- drawings';
SELECT format('INSERT INTO "drawings" ("id", "drawing_code", "project_id", "title", "discipline", "current_rev", "status", "drawn_by", "checked_by", "approved_by", "file_url", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."drawing_code", t."project_id", t."title", t."discipline", t."current_rev", t."status", t."drawn_by", t."checked_by", t."approved_by", t."file_url", t."created_at", t."updated_at") FROM "drawings" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- bill_of_materials';
SELECT format('INSERT INTO "bill_of_materials" ("id", "bom_code", "project_id", "name", "revision", "status", "created_by", "approved_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."bom_code", t."project_id", t."name", t."revision", t."status", t."created_by", t."approved_by", t."created_at", t."updated_at") FROM "bill_of_materials" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- engineering_change_orders';
SELECT format('INSERT INTO "engineering_change_orders" ("id", "eco_code", "project_id", "title", "description", "change_type", "impact_cost", "impact_schedule", "status", "requested_by", "approved_by", "approved_at", "implemented_at", "created_at", "updated_at", "source", "cost_bearer", "ncr_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."eco_code", t."project_id", t."title", t."description", t."change_type", t."impact_cost", t."impact_schedule", t."status", t."requested_by", t."approved_by", t."approved_at", t."implemented_at", t."created_at", t."updated_at", t."source", t."cost_bearer", t."ncr_id") FROM "engineering_change_orders" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- non_conformance_reports';
SELECT format('INSERT INTO "non_conformance_reports" ("id", "ncr_code", "project_id", "category", "severity", "description", "root_cause", "disposition", "rework_count", "status", "raised_by", "closed_by", "closed_at", "created_at", "updated_at", "task_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."ncr_code", t."project_id", t."category", t."severity", t."description", t."root_cause", t."disposition", t."rework_count", t."status", t."raised_by", t."closed_by", t."closed_at", t."created_at", t."updated_at", t."task_id") FROM "non_conformance_reports" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- subcontractor_contracts';
SELECT format('INSERT INTO "subcontractor_contracts" ("id", "project_id", "contract_code", "vendor_id", "description", "contract_value", "currency", "start_date", "end_date", "status", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."contract_code", t."vendor_id", t."description", t."contract_value", t."currency", t."start_date", t."end_date", t."status", t."created_at", t."updated_at") FROM "subcontractor_contracts" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- wbs_nodes';
SELECT format('INSERT INTO "wbs_nodes" ("id", "project_id", "parent_id", "node_code", "name", "name_en", "weight", "sort_order") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."parent_id", t."node_code", t."name", t."name_en", t."weight", t."sort_order") FROM "wbs_nodes" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- milestones';
SELECT format('INSERT INTO "milestones" ("id", "project_id", "name", "name_en", "description", "billing_percent", "planned_date", "actual_date", "status", "sort_order", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."name", t."name_en", t."description", t."billing_percent", t."planned_date", t."actual_date", t."status", t."sort_order", t."created_at") FROM "milestones" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- purchase_requests';
SELECT format('INSERT INTO "purchase_requests" ("id", "pr_code", "project_id", "requested_by", "status", "urgency", "notes", "approved_by", "approved_at", "created_at", "updated_at", "origin_type", "origin_id", "origin_label", "source_task_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."pr_code", t."project_id", t."requested_by", t."status", t."urgency", t."notes", t."approved_by", t."approved_at", t."created_at", t."updated_at", t."origin_type", t."origin_id", t."origin_label", t."source_task_id") FROM "purchase_requests" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- project_documents';
SELECT format('INSERT INTO "project_documents" ("id", "project_id", "doc_code", "doc_type", "revision", "dept_code", "title", "file_attachment_id", "task_id", "status", "uploaded_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."doc_code", t."doc_type", t."revision", t."dept_code", t."title", t."file_attachment_id", t."task_id", t."status", t."uploaded_by", t."created_at", t."updated_at") FROM "project_documents" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- bid_analyses';
SELECT format('INSERT INTO "bid_analyses" ("id", "project_id", "bid_code", "bid_code_proj", "bid_code_yymm", "bid_code_mat", "bid_code_seq", "bid_code_variant", "bid_code_urgent", "subject", "bid_date", "status", "selection_mode", "selected_vendor_id", "source_task_id", "notes", "created_by", "created_at", "updated_at", "legacy_bid_code", "source_file_name", "source_file_path", "weighting_criteria", "approved_by", "approved_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."bid_code", t."bid_code_proj", t."bid_code_yymm", t."bid_code_mat", t."bid_code_seq", t."bid_code_variant", t."bid_code_urgent", t."subject", t."bid_date", t."status", t."selection_mode", t."selected_vendor_id", t."source_task_id", t."notes", t."created_by", t."created_at", t."updated_at", t."legacy_bid_code", t."source_file_name", t."source_file_path", t."weighting_criteria", t."approved_by", t."approved_at") FROM "bid_analyses" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- fabrication_categories';
SELECT format('INSERT INTO "fabrication_categories" ("id", "project_id", "code", "name", "sort_order", "ghi_chu", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."code", t."name", t."sort_order", t."ghi_chu", t."created_at", t."updated_at") FROM "fabrication_categories" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- ledger_entries';
SELECT format('INSERT INTO "ledger_entries" ("id", "batch_id", "entry_date", "doc_type", "doc_no", "partner_code", "partner_name", "description", "account", "contra_account", "debit", "credit", "vu_viec", "project_id", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."batch_id", t."entry_date", t."doc_type", t."doc_no", t."partner_code", t."partner_name", t."description", t."account", t."contra_account", t."debit", t."credit", t."vu_viec", t."project_id", t."created_at") FROM "ledger_entries" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- purchase_contracts';
SELECT format('INSERT INTO "purchase_contracts" ("id", "contract_code", "contract_type", "project_id", "vendor_id", "title", "value", "currency", "signed_date", "effective_date", "payment_terms", "delivery_terms", "status", "signed_file_id", "notes", "created_by", "created_at", "updated_at", "trade_type", "vendor_country", "export_port", "import_lc_date", "cif_date", "payment_date", "customs_date", "arrived_date", "qc_invitation_date") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."contract_code", t."contract_type", t."project_id", t."vendor_id", t."title", t."value", t."currency", t."signed_date", t."effective_date", t."payment_terms", t."delivery_terms", t."status", t."signed_file_id", t."notes", t."created_by", t."created_at", t."updated_at", t."trade_type", t."vendor_country", t."export_port", t."import_lc_date", t."cif_date", t."payment_date", t."customs_date", t."arrived_date", t."qc_invitation_date") FROM "purchase_contracts" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- material_request_orders';
SELECT format('INSERT INTO "material_request_orders" ("id", "code", "project_id", "department_id", "status", "notes", "created_by", "submitted_at", "pm_approved_by", "pm_approved_at", "bod_approved_by", "bod_approved_at", "rejected_by", "rejected_at", "reject_reason", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."code", t."project_id", t."department_id", t."status", t."notes", t."created_by", t."submitted_at", t."pm_approved_by", t."pm_approved_at", t."bod_approved_by", t."bod_approved_at", t."rejected_by", t."rejected_at", t."reject_reason", t."created_at", t."updated_at") FROM "material_request_orders" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- purchase_orders';
SELECT format('INSERT INTO "purchase_orders" ("id", "po_code", "vendor_id", "status", "total_value", "currency", "order_date", "delivery_date", "payment_terms", "created_by", "notes", "created_at", "updated_at", "project_id", "source_task_id", "contract_id", "bid_analysis_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."po_code", t."vendor_id", t."status", t."total_value", t."currency", t."order_date", t."delivery_date", t."payment_terms", t."created_by", t."notes", t."created_at", t."updated_at", t."project_id", t."source_task_id", t."contract_id", t."bid_analysis_id") FROM "purchase_orders" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- quote_groups';
SELECT format('INSERT INTO "quote_groups" ("id", "task_id", "project_id", "group_key", "name", "status", "total_value", "pr_code", "payment_status", "delivery_date", "payment_date", "assigned_supplier", "rejected_reason", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."task_id", t."project_id", t."group_key", t."name", t."status", t."total_value", t."pr_code", t."payment_status", t."delivery_date", t."payment_date", t."assigned_supplier", t."rejected_reason", t."created_at", t."updated_at") FROM "quote_groups" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- purchase_request_items';
SELECT format('INSERT INTO "purchase_request_items" ("id", "pr_id", "material_id", "quantity", "required_date", "specification", "notes", "bom_item_id", "bom_version_id", "item_code", "item_description", "item_profile", "item_grade", "item_unit", "material_group_code", "material_sub_group_code", "unit_weight", "net_qty", "net_weight", "req_qty", "req_weight", "remain_qty", "remain_weight", "to_buy_qty", "to_buy_weight", "status_flag", "remarks", "mat_code", "mat_code_source") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."pr_id", t."material_id", t."quantity", t."required_date", t."specification", t."notes", t."bom_item_id", t."bom_version_id", t."item_code", t."item_description", t."item_profile", t."item_grade", t."item_unit", t."material_group_code", t."material_sub_group_code", t."unit_weight", t."net_qty", t."net_weight", t."req_qty", t."req_weight", t."remain_qty", t."remain_weight", t."to_buy_qty", t."to_buy_weight", t."status_flag", t."remarks", t."mat_code", t."mat_code_source") FROM "purchase_request_items" t WHERE pr_id in (select id from purchase_requests where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- ncr_actions';
SELECT format('INSERT INTO "ncr_actions" ("id", "ncr_id", "action_type", "description", "assigned_to", "due_date", "completed_at", "status", "evidence", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."ncr_id", t."action_type", t."description", t."assigned_to", t."due_date", t."completed_at", t."status", t."evidence", t."created_at") FROM "ncr_actions" t WHERE ncr_id in (select id from non_conformance_reports where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- drawing_revisions';
SELECT format('INSERT INTO "drawing_revisions" ("id", "drawing_id", "revision", "description", "issued_date", "issued_by", "file_url", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."drawing_id", t."revision", t."description", t."issued_date", t."issued_by", t."file_url", t."created_at") FROM "drawing_revisions" t WHERE drawing_id in (select id from drawings where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- project_budget_lines';
SELECT format('INSERT INTO "project_budget_lines" ("id", "plan_id", "section_type", "category_code", "item_name", "unit", "quantity", "unit_price", "total_budget") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."plan_id", t."section_type", t."category_code", t."item_name", t."unit", t."quantity", t."unit_price", t."total_budget") FROM "project_budget_lines" t WHERE plan_id in (select id from project_finance_plans where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- project_cashflow_monthly';
SELECT format('INSERT INTO "project_cashflow_monthly" ("id", "plan_id", "month", "year", "amount_vnd", "category", "notes") VALUES (%L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."plan_id", t."month", t."year", t."amount_vnd", t."category", t."notes") FROM "project_cashflow_monthly" t WHERE plan_id in (select id from project_finance_plans where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- monthly_piece_rate_outputs';
SELECT format('INSERT INTO "monthly_piece_rate_outputs" ("id", "contract_id", "month", "year", "quantity", "unit_price", "total_amount", "verified_by", "status", "notes", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."contract_id", t."month", t."year", t."quantity", t."unit_price", t."total_amount", t."verified_by", t."status", t."notes", t."created_at") FROM "monthly_piece_rate_outputs" t WHERE contract_id in (select id from piece_rate_contracts where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- task_assignees';
SELECT format('INSERT INTO "task_assignees" ("id", "task_id", "role", "user_id", "is_primary", "accepted_at", "created_at", "done", "done_at", "done_by", "outcome") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."task_id", t."role", t."user_id", t."is_primary", t."accepted_at", t."created_at", t."done", t."done_at", t."done_by", t."outcome") FROM "task_assignees" t WHERE task_id in (select id from tasks where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- task_doc_requirements';
SELECT format('INSERT INTO "task_doc_requirements" ("id", "task_id", "kind", "label", "file_attachment_id", "fulfilled", "created_at", "note") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."task_id", t."kind", t."label", t."file_attachment_id", t."fulfilled", t."created_at", t."note") FROM "task_doc_requirements" t WHERE task_id in (select id from tasks where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- task_history';
SELECT format('INSERT INTO "task_history" ("id", "task_id", "action", "by_user_id", "from_user_id", "to_role", "to_user_id", "reason", "meta", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."task_id", t."action", t."by_user_id", t."from_user_id", t."to_role", t."to_user_id", t."reason", t."meta", t."created_at") FROM "task_history" t WHERE task_id in (select id from tasks where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- meeting_invites';
SELECT format('INSERT INTO "meeting_invites" ("id", "meeting_id", "user_id", "status", "responded_at", "note", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."meeting_id", t."user_id", t."status", t."responded_at", t."note", t."created_at") FROM "meeting_invites" t WHERE meeting_id in (select id from meetings where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- shipment_items';
SELECT format('INSERT INTO "shipment_items" ("id", "shipment_id", "packing_list_id", "loaded_at", "created_at") VALUES (%L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."shipment_id", t."packing_list_id", t."loaded_at", t."created_at") FROM "shipment_items" t WHERE shipment_id in (select id from shipments where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- bid_quote_vendors';
SELECT format('INSERT INTO "bid_quote_vendors" ("id", "bid_id", "vendor_id", "vendor_name", "vendor_type", "vendor_order", "currency", "total_quote", "is_winner", "notes", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."bid_id", t."vendor_id", t."vendor_name", t."vendor_type", t."vendor_order", t."currency", t."total_quote", t."is_winner", t."notes", t."created_at") FROM "bid_quote_vendors" t WHERE bid_id in (select id from bid_analyses where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- bid_group_selections';
SELECT format('INSERT INTO "bid_group_selections" ("id", "bid_analysis_id", "material_sub_group_code", "selected_vendor_name", "selected_at", "selected_by", "notes") VALUES (%L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."bid_analysis_id", t."material_sub_group_code", t."selected_vendor_name", t."selected_at", t."selected_by", t."notes") FROM "bid_group_selections" t WHERE bid_analysis_id in (select id from bid_analyses where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- bid_vendor_scores';
SELECT format('INSERT INTO "bid_vendor_scores" ("id", "bid_analysis_id", "vendor_name", "price_score", "quality_score", "payment_score", "overall_score", "scored_at", "scored_by", "notes") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."bid_analysis_id", t."vendor_name", t."price_score", t."quality_score", t."payment_score", t."overall_score", t."scored_at", t."scored_by", t."notes") FROM "bid_vendor_scores" t WHERE bid_analysis_id in (select id from bid_analyses where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- invoices';
SELECT format('INSERT INTO "invoices" ("id", "invoice_code", "project_id", "vendor_id", "type", "client_name", "description", "amount", "tax_rate", "tax_amount", "total_amount", "currency", "issue_date", "due_date", "paid_amount", "status", "notes", "created_at", "updated_at", "po_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."invoice_code", t."project_id", t."vendor_id", t."type", t."client_name", t."description", t."amount", t."tax_rate", t."tax_amount", t."total_amount", t."currency", t."issue_date", t."due_date", t."paid_amount", t."status", t."notes", t."created_at", t."updated_at", t."po_id") FROM "invoices" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- payment_schedules';
SELECT format('INSERT INTO "payment_schedules" ("id", "project_id", "purchase_order_id", "supplier", "sale_contract", "value", "currency", "payment_method", "sign_date", "lc_date", "etd", "eta", "document_date", "lc_deadline", "payment_month", "status", "paid_date", "paid_amount", "notes", "created_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."purchase_order_id", t."supplier", t."sale_contract", t."value", t."currency", t."payment_method", t."sign_date", t."lc_date", t."etd", t."eta", t."document_date", t."lc_deadline", t."payment_month", t."status", t."paid_date", t."paid_amount", t."notes", t."created_by", t."created_at", t."updated_at") FROM "payment_schedules" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- hard_peggings';
SELECT format('INSERT INTO "hard_peggings" ("id", "pr_item_id", "material_id", "project_id", "quantity", "status", "note", "allocated_by", "allocated_at", "released_by", "released_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."pr_item_id", t."material_id", t."project_id", t."quantity", t."status", t."note", t."allocated_by", t."allocated_at", t."released_by", t."released_at") FROM "hard_peggings" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- purchase_order_items';
SELECT format('INSERT INTO "purchase_order_items" ("id", "po_id", "material_id", "quantity", "unit_price", "received_qty", "notes", "item_code", "item_description", "item_profile", "item_grade", "item_unit") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."po_id", t."material_id", t."quantity", t."unit_price", t."received_qty", t."notes", t."item_code", t."item_description", t."item_profile", t."item_grade", t."item_unit") FROM "purchase_order_items" t WHERE po_id in (select id from purchase_orders where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- task_doc_acks';
SELECT format('INSERT INTO "task_doc_acks" ("id", "requirement_id", "user_id", "created_at") VALUES (%L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."requirement_id", t."user_id", t."created_at") FROM "task_doc_acks" t WHERE requirement_id in (select id from task_doc_requirements where task_id in (select id from tasks where project_id = (select id from projects where project_code = '26-VPI-I-113')));

SELECT '-- bom_versions';
SELECT format('INSERT INTO "bom_versions" ("id", "bom_id", "version_no", "status", "source_revision_id", "eco_id", "reason", "created_by", "approved_by", "approved_at", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."bom_id", t."version_no", t."status", t."source_revision_id", t."eco_id", t."reason", t."created_by", t."approved_by", t."approved_at", t."created_at", t."updated_at") FROM "bom_versions" t WHERE bom_id in (select id from bill_of_materials where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- bid_quote_items';
SELECT format('INSERT INTO "bid_quote_items" ("id", "bid_id", "purchase_request_item_id", "item_order", "item_code", "item_name", "profile", "grade", "uom", "qty_pr", "qty_to_buy", "estimate_unit_price", "selected_vendor_name", "notes", "created_at", "already_bought_amount", "selected_at", "selected_by") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."bid_id", t."purchase_request_item_id", t."item_order", t."item_code", t."item_name", t."profile", t."grade", t."uom", t."qty_pr", t."qty_to_buy", t."estimate_unit_price", t."selected_vendor_name", t."notes", t."created_at", t."already_bought_amount", t."selected_at", t."selected_by") FROM "bid_quote_items" t WHERE bid_id in (select id from bid_analyses where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- pr_item_fab_allocations';
SELECT format('INSERT INTO "pr_item_fab_allocations" ("id", "pr_item_id", "fabrication_category_id", "qty", "weight", "ngay_can_tai_cong_truong", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."pr_item_id", t."fabrication_category_id", t."qty", t."weight", t."ngay_can_tai_cong_truong", t."created_at", t."updated_at") FROM "pr_item_fab_allocations" t WHERE pr_item_id in (select id from purchase_request_items where pr_id in (select id from purchase_requests where project_id = (select id from projects where project_code = '26-VPI-I-113')));

SELECT '-- tech_comments';
SELECT format('INSERT INTO "tech_comments" ("id", "pr_item_id", "author_id", "content", "comment_type", "thread_status", "tags", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."pr_item_id", t."author_id", t."content", t."comment_type", t."thread_status", t."tags", t."created_at", t."updated_at") FROM "tech_comments" t WHERE pr_item_id in (select id from purchase_request_items where pr_id in (select id from purchase_requests where project_id = (select id from projects where project_code = '26-VPI-I-113')));

SELECT '-- purchase_contract_items';
SELECT format('INSERT INTO "purchase_contract_items" ("id", "contract_id", "pr_item_id", "material_id", "item_code", "description", "unit", "actual_profile", "actual_grade", "contract_qty", "contract_weight", "unit_price_no_vat", "currency", "vat_rate", "total_no_vat", "total_with_vat", "delivered_qty", "delivered_weight", "handover_date", "line_status", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."contract_id", t."pr_item_id", t."material_id", t."item_code", t."description", t."unit", t."actual_profile", t."actual_grade", t."contract_qty", t."contract_weight", t."unit_price_no_vat", t."currency", t."vat_rate", t."total_no_vat", t."total_with_vat", t."delivered_qty", t."delivered_weight", t."handover_date", t."line_status", t."created_at") FROM "purchase_contract_items" t WHERE contract_id in (select id from purchase_contracts where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- quote_group_items';
SELECT format('INSERT INTO "quote_group_items" ("id", "quote_group_id", "name", "code", "spec", "unit", "source", "quantity", "requested_qty", "in_stock", "shortfall", "spec_match", "matched_material", "selected_quote_index", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."quote_group_id", t."name", t."code", t."spec", t."unit", t."source", t."quantity", t."requested_qty", t."in_stock", t."shortfall", t."spec_match", t."matched_material", t."selected_quote_index", t."created_at", t."updated_at") FROM "quote_group_items" t WHERE quote_group_id in (select id from quote_groups where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- customer_receipts';
SELECT format('INSERT INTO "customer_receipts" ("id", "invoice_id", "project_id", "amount", "method", "received_at", "reference_no", "notes", "created_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."invoice_id", t."project_id", t."amount", t."method", t."received_at", t."reference_no", t."notes", t."created_by", t."created_at", t."updated_at") FROM "customer_receipts" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- work_orders';
SELECT format('INSERT INTO "work_orders" ("id", "wo_code", "project_id", "description", "team_code", "status", "planned_start", "planned_end", "actual_start", "actual_end", "created_by", "created_at", "updated_at", "completed_qty", "quantity", "wo_type", "workshop_id", "piece_mark", "bom_version_id", "planned_weight", "department_id", "earned_qty", "needs_re_qc", "re_qc_reason") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."wo_code", t."project_id", t."description", t."team_code", t."status", t."planned_start", t."planned_end", t."actual_start", t."actual_end", t."created_by", t."created_at", t."updated_at", t."completed_qty", t."quantity", t."wo_type", t."workshop_id", t."piece_mark", t."bom_version_id", t."planned_weight", t."department_id", t."earned_qty", t."needs_re_qc", t."re_qc_reason") FROM "work_orders" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- bom_items';
SELECT format('INSERT INTO "bom_items" ("id", "bom_id", "material_id", "parent_id", "quantity", "unit", "remarks", "sort_order", "bom_version_id", "category", "piece_mark", "profile", "grade", "layer", "surface_area_m2", "weld_length_m") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."bom_id", t."material_id", t."parent_id", t."quantity", t."unit", t."remarks", t."sort_order", t."bom_version_id", t."category", t."piece_mark", t."profile", t."grade", t."layer", t."surface_area_m2", t."weld_length_m") FROM "bom_items" t WHERE bom_id in (select id from bill_of_materials where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- payments';
SELECT format('INSERT INTO "payments" ("id", "invoice_id", "amount", "payment_date", "method", "reference", "notes", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."invoice_id", t."amount", t."payment_date", t."method", t."reference", t."notes", t."created_at") FROM "payments" t WHERE invoice_id in (select id from invoices where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- drawdown_beneficiary_lines';
SELECT format('INSERT INTO "drawdown_beneficiary_lines" ("id", "drawdown_id", "sequence_no", "vendor_id", "invoice_id", "invoice_number", "amount_vnd", "bank_account_no", "bank_name", "notes", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."drawdown_id", t."sequence_no", t."vendor_id", t."invoice_id", t."invoice_number", t."amount_vnd", t."bank_account_no", t."bank_name", t."notes", t."created_at") FROM "drawdown_beneficiary_lines" t WHERE invoice_id in (select id from invoices where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- bid_quote_offers';
SELECT format('INSERT INTO "bid_quote_offers" ("id", "item_id", "vendor_id", "unit_price", "total_price", "scope", "delivery_term", "remarks", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."item_id", t."vendor_id", t."unit_price", t."total_price", t."scope", t."delivery_term", t."remarks", t."created_at") FROM "bid_quote_offers" t WHERE item_id in (select id from bid_quote_items where bid_id in (select id from bid_analyses where project_id = (select id from projects where project_code = '26-VPI-I-113')));

SELECT '-- contract_inspections';
SELECT format('INSERT INTO "contract_inspections" ("id", "contract_item_id", "inspection_type", "report_no", "inspection_date", "inspected_qty", "inspected_weight", "accepted_qty", "accepted_weight", "result", "remarks", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."contract_item_id", t."inspection_type", t."report_no", t."inspection_date", t."inspected_qty", t."inspected_weight", t."accepted_qty", t."accepted_weight", t."result", t."remarks", t."created_at") FROM "contract_inspections" t WHERE contract_item_id in (select id from purchase_contract_items where contract_id in (select id from purchase_contracts where project_id = (select id from projects where project_code = '26-VPI-I-113')));

SELECT '-- supplier_quote_lines';
SELECT format('INSERT INTO "supplier_quote_lines" ("id", "item_id", "line_index", "supplier_name", "unit_price", "created_at") VALUES (%L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."item_id", t."line_index", t."supplier_name", t."unit_price", t."created_at") FROM "supplier_quote_lines" t WHERE item_id in (select id from quote_group_items where quote_group_id in (select id from quote_groups where project_id = (select id from projects where project_code = '26-VPI-I-113')));

SELECT '-- delivery_records';
SELECT format('INSERT INTO "delivery_records" ("id", "delivery_code", "project_id", "work_order_id", "status", "packing_list", "shipping_method", "tracking_no", "shipped_at", "delivered_at", "received_by", "notes", "created_by", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."delivery_code", t."project_id", t."work_order_id", t."status", t."packing_list", t."shipping_method", t."tracking_no", t."shipped_at", t."delivered_at", t."received_by", t."notes", t."created_by", t."created_at", t."updated_at") FROM "delivery_records" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- inspections';
SELECT format('INSERT INTO "inspections" ("id", "project_id", "inspection_code", "type", "step_code", "status", "inspector_id", "inspected_at", "result_data", "remarks", "created_at", "updated_at", "work_order_id", "piece_mark") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."project_id", t."inspection_code", t."type", t."step_code", t."status", t."inspector_id", t."inspected_at", t."result_data", t."remarks", t."created_at", t."updated_at", t."work_order_id", t."piece_mark") FROM "inspections" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- work_permits';
SELECT format('INSERT INTO "work_permits" ("id", "permit_code", "permit_type", "project_id", "work_order_id", "location", "description", "hazards", "precautions", "valid_from", "valid_to", "status", "requested_by", "approved_by", "approved_at", "closed_by", "closed_at", "notes", "created_at", "updated_at", "task_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."permit_code", t."permit_type", t."project_id", t."work_order_id", t."location", t."description", t."hazards", t."precautions", t."valid_from", t."valid_to", t."status", t."requested_by", t."approved_by", t."approved_at", t."closed_by", t."closed_at", t."notes", t."created_at", t."updated_at", t."task_id") FROM "work_permits" t WHERE project_id = (select id from projects where project_code = '26-VPI-I-113');

SELECT '-- material_issues';
SELECT format('INSERT INTO "material_issues" ("id", "work_order_id", "material_id", "quantity", "issued_by", "issued_at", "notes", "heat_number") VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."work_order_id", t."material_id", t."quantity", t."issued_by", t."issued_at", t."notes", t."heat_number") FROM "material_issues" t WHERE work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- job_cards';
SELECT format('INSERT INTO "job_cards" ("id", "job_code", "work_order_id", "team_code", "work_type", "description", "planned_qty", "actual_qty", "unit", "work_date", "start_time", "end_time", "manpower", "status", "reported_by", "approved_by", "notes", "created_at", "updated_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."job_code", t."work_order_id", t."team_code", t."work_type", t."description", t."planned_qty", t."actual_qty", t."unit", t."work_date", t."start_time", t."end_time", t."manpower", t."status", t."reported_by", t."approved_by", t."notes", t."created_at", t."updated_at") FROM "job_cards" t WHERE work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- itp_checkpoints';
SELECT format('INSERT INTO "itp_checkpoints" ("id", "itp_id", "checkpoint_no", "activity", "description", "standard", "accept_criteria", "inspection_type", "status", "inspected_by", "inspected_at", "remarks", "sort_order", "ncr_id", "work_order_id", "piece_mark") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."itp_id", t."checkpoint_no", t."activity", t."description", t."standard", t."accept_criteria", t."inspection_type", t."status", t."inspected_by", t."inspected_at", t."remarks", t."sort_order", t."ncr_id", t."work_order_id", t."piece_mark") FROM "itp_checkpoints" t WHERE itp_id in (select id from inspection_test_plans where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- weld_joints';
SELECT format('INSERT INTO "weld_joints" ("id", "work_order_id", "joint_no", "joint_type", "wps_no", "welder_id", "welder_cert_id", "diameter", "thickness", "length", "status", "welded_at", "ndt_status", "ndt_method", "ncr_id", "remarks", "created_at", "updated_at", "wps_cert_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."work_order_id", t."joint_no", t."joint_type", t."wps_no", t."welder_id", t."welder_cert_id", t."diameter", t."thickness", t."length", t."status", t."welded_at", t."ndt_status", t."ndt_method", t."ncr_id", t."remarks", t."created_at", t."updated_at", t."wps_cert_id") FROM "weld_joints" t WHERE work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- packing_list_items';
SELECT format('INSERT INTO "packing_list_items" ("id", "packing_list_id", "work_order_id", "piece_mark", "description", "weight", "quantity", "qc_status", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."packing_list_id", t."work_order_id", t."piece_mark", t."description", t."weight", t."quantity", t."qc_status", t."created_at") FROM "packing_list_items" t WHERE packing_list_id in (select id from packing_lists where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- equipment_assignments';
SELECT format('INSERT INTO "equipment_assignments" ("id", "equipment_id", "work_order_id", "department_id", "assigned_from", "assigned_to", "status", "notes", "created_by", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."equipment_id", t."work_order_id", t."department_id", t."assigned_from", t."assigned_to", t."status", t."notes", t."created_by", t."created_at") FROM "equipment_assignments" t WHERE work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- work_order_material_requests';
SELECT format('INSERT INTO "work_order_material_requests" ("id", "work_order_id", "material_id", "quantity", "unit", "source", "notes", "created_by", "created_at", "updated_at", "request_id") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."work_order_id", t."material_id", t."quantity", t."unit", t."source", t."notes", t."created_by", t."created_at", t."updated_at", t."request_id") FROM "work_order_material_requests" t WHERE work_order_id in (select id from work_orders where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- inspection_items';
SELECT format('INSERT INTO "inspection_items" ("id", "inspection_id", "check_item", "standard", "result", "measurement", "notes") VALUES (%L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."inspection_id", t."check_item", t."standard", t."result", t."measurement", t."notes") FROM "inspection_items" t WHERE inspection_id in (select id from inspections where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- file_attachments';
SELECT format('INSERT INTO "file_attachments" ("id", "entity_type", "entity_id", "file_name", "file_url", "file_size", "mime_type", "uploaded_by", "created_at") VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT DO NOTHING;', t."id", t."entity_type", t."entity_id", t."file_name", t."file_url", t."file_size", t."mime_type", t."uploaded_by", t."created_at") FROM "file_attachments" t WHERE t."entity_id" = (select id from projects where project_code = '26-VPI-I-113')
   OR split_part(t."entity_id", '_', 1) IN (select id from tasks    where project_id = (select id from projects where project_code = '26-VPI-I-113'))
   OR split_part(t."entity_id", '_', 1) IN (select id from meetings where project_id = (select id from projects where project_code = '26-VPI-I-113'));

SELECT '-- HẾT';
